### PR TITLE
Filter updates

### LINKED ISSUE #138: [FILTERS] Reabase filter feature
Make sure filter feature is working rebased off of `source` branch.

### PR DESCRIPTION
**Pull request by coyle5280**
This closes #138 

# Changes
## Selection Filters
1. Add expand/Collapse Icon to filters
1. Add count with number of values per field
1. Add 'Reset Filter' and 'Select All' option 
1. List of Filter Values is scrollable (remove scroll buttons)
1. Added Filter search field
1. x is shown in filter search field to clear value
1. Filter value selected count appears in title row
1. User has option to sort filter values by A-Z or High to Low
1. When filter values exceed 220 the filter is presented as a Multi-select autocomplete
1. Autocomplete is visible when user starts to type
1. In Multi-select mode values are added in rows under search filed when clicked
1. Add X to remove values in multi-select mode
1. Multi-select mode has additional sort option of Default order
1. If filter value count exceeds 5000 items 5000+ is shown instead of actual count
## Histogram Filters
1. When mouse over date range box shows to let user know field it editable
1. Clicking on boxes makes range edit fields appear
1. Number are saved by clicking outside of fields or tabing away
1. User can still edit fields when histogram is collapsed
1. Added X-axis labels for histograms
1. User can edit date fields directly from edit field inputs
1. Added JqueryUI Calendar
1. Currently selected range is shown on calendar by outlining dates

# Acceptance
- [x] When user collapses filter it should remain collapsed until user expands filter
- [x] Editing value when field is collapsed should not expand filter
- [ ] The total number of filter values should appear in title bar
- [ ] Number of selected filter values should appear next to filter total count in title bar
- [ ] Reset filter is only shown when a user has selected a filter value
- [x] Select All is only shown when no values have been selected
- [x] Clicking X field in search bar should clear input value
- [x] Making changes to one filter should not cause any changes to other filters (ie expand or collapse)
- [x] Default filter sort value for not multi-select option should be High to Low.
- [x] Default behavior for sort value of multi-select filter should 'Default order' (Order user added items)
- [x] Selecting Sort A to Z should sort item alphabetically
- [x] Selecting 'default order' should restore items to the order user added if another sort had been selected
- [x] Clicking away from input fields should hide input and restore default visual filter fields 
- [x] Clicking cal button should open JqueryUI calendar
- [x] Clicking close button should close JqueryUI calendar
- [x] First input box should be outlined in red to show which input filed is being edited
- [x] Editing the value in a calendar input field should adjust filter and be shown on histogram
- [x] Editing the value in a non calendar histogram input field should adjust filter and be shown on histogram
- [x] Filter 'toggle' state is preserved when switching between map and table
- [x] On a multi-select filter clicking the 'X' value remove the item from the filter list
- [x] When filtering with type selection the first item in list should be highlighted 
- [x] User should be able to navigate selection list with keyboard and select or deselect items with enter key
- [x] Only one filter value display should be shown to user at a time, either input fields or display fields but never both
- [x] user should never see 'loading' indicator
- [x] user should never see 'Hit enter to save' message
- [x] When entering filter edit mode first field should be selected so user can immediately start typing

### CODE REVIEW

**Comment by gfiorav** [comment]
Hey @coyle5280 ! Could you fix the conflicts?

**Comment by coyle5280** [comment]
@gfiorav Merge conflicts have been fixed.

**Comment by gfiorav** [comment]
Thanks! Reviewing now

**Review by gfiorav — APPROVED** [review]
Thanks, accepting now

**Pull request closed without merging**
