### PR TITLE
Feature/categorical filtering

### PR DESCRIPTION
**Pull request by CloudNiner**
bbg-filtering

And the generated SQL:
bbg-filtering-sql

### CODE REVIEW

**Comment by mbforr** [comment]
Looks great. Are we ready to test?

**Comment by CloudNiner** [comment]
@ddohler realize you're swamped ATM, feel free to review later, going to merge so that the cartodb folks can start testing, will cleanup any code review issues as necessary.

**Comment by CloudNiner** [comment]
@mbforr sure go ahead

**Comment by CloudNiner** [comment]
@javisantana if you want to review this as well that would be great.

**Comment by javisantana** [comment]
@CloudNiner we usually review before merge. You should also try to setup travis to run frontend specs: https://github.com/CartoDB/cartodb/blob/master/.travis.yml

**Comment by CloudNiner** [comment]
Ah, yeah I jumped the gun on this one. We'll look into setting up travis for this repo and I have a test or two to fix. Will update in a separate PR.

**Comment by ddohler** [comment]
Code looks good, fwiw.

**Pull request merged**
