### PR TITLE
Reorder and reformat toolbar for maps and datasets

### PR DESCRIPTION
**Pull request by sharph**

### CODE REVIEW

**Comment by CloudNiner** [comment]
I've got some wonky text if I select a dataset on the Datasets page:
bbg-datasets-selected

**Comment by CloudNiner** [comment]
I added the remaining items to complete here:
https://github.com/cartodb-org/cartodb/issues/109#issuecomment-240175366
by referencing the wireframes in issue #109. Was the intention with this PR to totally complete this task, or just a subset of it?

**Comment by sharph** [comment]
The intention of this PR is to clear the cards "reorder maps toolbar" and "reorder datasets toolbar." I'm unable to reproduce your wonky text. Maybe it's an issue with submodules?

**Comment by CloudNiner** [comment]
Hmmm, I'll see if I can get the weirdness to show up on my work vm tomorrow. 

In that case, the remaining items in the linked comment still need to be addressed. Most of them should be pretty quick, I can work on some tomorrow as well to finish this up faster.

**Comment by CloudNiner** [comment]
Unable to reproduce the weird styles I was seeing yesterday.

**Comment by CloudNiner** [comment]
+1

**Pull request merged**
