### PR TITLE
Fix inset map stray shadow box svg issue

### PR DESCRIPTION
**Pull request by fungjj92**
Video of action: [svginsetbugfix.zip](https://github.com/cartodb-org/cartodb/files/362322/svginsetbugfix.zip)

### CODE REVIEW

**Comment by CloudNiner** [comment]
Looks like this fix is in the leaflet control. Hotfixing the js file is ok for now, but since this is a bug in the minimap control, it would be worth submitting a pull request against the library that fixes it there. Then we can pull in the updated upstream code without worrying that this fix will go away if we ever update the library in cartodb.

**Comment by fungjj92** [comment]
Which file is the leaflet control?

**Comment by CloudNiner** [comment]
The file you modified in the PR, which was copied directly from here: https://github.com/Norkart/Leaflet-MiniMap

**Comment by CloudNiner** [comment]
LGTM. Next sprint we'll try reproducing in the upstream repository and fixing it there.

**Pull request merged**
