### PR TITLE
Remove map preview button and rename edit button

### PR DESCRIPTION
**Pull request by fungjj92**
screen shot 2016-07-05 at 3 18 52 pm

Remove preview map button.
Restyle actions dropdown.

### CODE REVIEW

**Comment by mbforr** [comment]
Looks good but can we move the 'Actions' button and 'Table/Map' toggle down into the grey space 

screen shot 2016-07-06 at 9 18 03 am

**Comment by fungjj92** [comment]
@mbforr We were going to use the top blue bar as the toolbar since it already spans the width of the page and lives above the layers panel, as desired in the wireframes. The blue bar will just need simple restyling, then. Should map annotations continue overlaying the toolbar when active?

**Comment by mbforr** [comment]
Ah I see okay that should work then - so removing the white area completely? And annotations as in the 'Annotate' dropdown?

**Comment by CloudNiner** [comment]
LGTM

**Pull request merged**
