### PR TITLE
Use crosshair cursor in image export

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Show crosshair cursor anywhere on map overlay during image export.

### CODE REVIEW

**Comment by rmartz** [comment]
Just want to check it's intentional, I'm seeing the crosshairs by default when nothing is being dragged, four-way arrow when I'm moving the viewport, but crosshairs when I'm scrolling the entire map. Is that what we want or should it be four-way arrow when anything is being moved?

There's also a weird interaction with the "create dataset from query or clear view or dismiss." message banner... the cursor changes from crosshairs to four-way arrow if it passes over it while dragging the map.

**Comment by flibbertigibbet** [comment]
The feedback we got was "Change it to the crosshairs for standard sizes" and "Change cursor to drag when moving it on screen." There's already a drag cursor during drag events on custom resize, so I just put the crosshair cursor on the export overlay otherwise. The dismiss banner is a separate thing to interact with and outside the export overlay.

Do you think we're supposed to do something else for this?

**Comment by rmartz** [comment]
I personally took "Change cursor to drag when moving it on screen." to mean moving anything (Including panning the map), not just moving the bounding box.

The dismiss banner is a bigger part but it goes over the export view it and feels unpolished to have a dragging cursor while passing over an unrelated component but not while over the thing you're dragging.

**Comment by flibbertigibbet** [comment]
Map pan is generalized behavior. It doesn't give a grab cursor out of export view either.

**Comment by rmartz** [comment]
Interesting, I could have sworn the standard map view gave a drag cursor while panning but looks like I'm mistaken, it's only when the mouse is over anything but the map that it does that.

:+1: Looks good to me!

**Comment by flibbertigibbet** [comment]
Standard leaflet does give a grab cursor by default, but cartodb has overridden that I think.

**Pull request merged**
