### PR TITLE
Persist SQL banner hide on toggle between map/data views.

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Will reappear on page refresh or after navigating up to the dashboard, then back in.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Should close #8.

**Comment by CloudNiner** [comment]
I loaded up this branch and the banner immediately dismisses on a fresh page load without interaction, I can show you if you want to stop by.

**Comment by flibbertigibbet** [comment]
Was unable to reproduce banner disappearance for map view, visualization, or with multiple layers. I did observe banner disappearing on query application, so I've made some slight modifications that sort that out. Please give it a try; if it works, I'll rebase this down.

**Comment by CloudNiner** [comment]
+1 that fixed my issue.

**Pull request merged**
